// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Conntrack = NewRuntimeAsset("conntrack.c", "87e076459597a0b7709fcd4981e64f015c90c2deb425af4da6ecce74e8863be9")
