// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "0b89295abbfac5c5fbc888a746e2c44469ec8173c604439379e70abc5d45a1a1")
