// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "bce6b4223e080371294f4d396098b256ff0c1a161b8acccabd06a2d0087de90e")
