// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "a6586c31a8dd4b4a9a04f61bc01aa2af2621afd73c2f27773065b4e0ba25af46")
